version: '3.8'

services:
  cbykApp:
    image: 'cbyk:latest'
    build:
      context: .
    container_name: cbykApp
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8083:8083"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=cbyk
    ports:
      - "5432:5432"